### ISSUE TITLE
As a FAC grad, I to do a simple filter by FAC cohort

### ISSUE THREAD

**Issue by helenzhou6** [fac-13/stackMatch#110]
- [ ] As a FAC grad, I can select a filter #76
- [ ] As a FAC grad, I can see the results of my filter #77
- [ ] As a FAC grad, I can remove my filter #78
