### ISSUE TITLE
As a FAC grad, I can view my saved profile

### ISSUE THREAD

**Issue by helenzhou6** [fac-13/stackMatch#14]
**Acceptance Criteria**

- [x] Create saved profile endpoint - issue #42
- [x] Query the database for relevant profile info - issue #43 
- [x] Autopopulate user details form with github info on signup - issue #71
- [x] Update page view with the profile info - issue #44 

Edit profile form mode:
![edit profile details](https://i.imgur.com/f42bYPa.png)

View profile mode:
![profile](https://i.imgur.com/d8jKzTw.png)

**Comment by helenzhou6** [comment]
Relate to user journey: #5
