### ISSUE TITLE
As a FAC grad, I can sign up to StackMatch, create my profile with Github info and then log out.

### ISSUE THREAD

**Issue by vlbee** [fac-13/stackMatch#5]
- [x] As a FAC grad, I can view a stackMatch homepage #6
- [x] As a FAC grad, I can click a sign up button to sign up via gitHub. #7
- [x] As a FAC grad, I can view my autopopulated initial profile #8
- [x] As a FAC grad, I can click a button to log out. #9
- [x] As a FAC grad, I can view my saved profile #14
