### ISSUE TITLE
As a FAC grad, I can view a stackMatch homepage

### ISSUE THREAD

**Issue by vlbee** [fac-13/stackMatch#6]
**Acceptance Criteria**

- [x] Set up handlebars view engine - issue #15
- [x] Split handlebars into partials - issue #16 
- [x] Serve static files via express - issue #17
- [x] Create '/' endpoint - issue #18
- [x] Make a basic layout landing page - issue #19
- [x] Create html sign up button - issue #20
- [ ] set up BEM and SASS compiler - issue #21
- [ ] add initial CSS styling - issue #22 
- [x] Error pages - 404 and 500 - issue #48

 ![First page of the app](https://i.imgur.com/TuLtliP.png)

**Comment by helenzhou6** [comment]
Relate to user journey: #5

**Comment by helenzhou6** [comment]
Basic CSS done, 
These issues have been added to the backlog milestone:
set up BEM and SASS compiler - issue #21
add initial CSS styling - issue #22
