### ISSUE TITLE
I can see all members of StackMatch in an single all users page 

### ISSUE THREAD

**Issue by helenzhou6** [fac-13/stackMatch#74]
User journey: #75 

**Acceptance Criteria**
- [x] add all users endpoint #79
- [x] sql query to get all members and basic information #80
- [x] handlebars view of all members #81  

![image](https://user-images.githubusercontent.com/32312712/40001713-bb6c64c4-5786-11e8-9bda-ba2d5234d60b.png)
