### ISSUE TITLE
As a FAC grad, I want to see all members of StackMatch and do a simple filter by FAC cohort

### ISSUE THREAD

**Issue by LawEKS** [fac-13/stackMatch#75]
**Acceptance Criteria**
- [x] As a FAC grad, I can see all members in a user list page #74 
- [x] As a FAC grad, I can click on a member card and it links to their profile page - issue #109
- [x] As a FAC grad, I can go to `profile/github_handle` to view another member's profile page - issue #113
