### ISSUE TITLE
As a FAC grad, I can review my autopopulated initial profile and save changes

### ISSUE THREAD

**Issue by vlbee** [fac-13/stackMatch#8]
**Acceptance Criteria**

- [x] request user info from GitHub API using access token - name, handle, avatar - issue #34
- [x] create profile review endpoint route - My Details section with name/fac/github/gitter links - issue #35
- [x] save button that inserts data into database - issue #36
- [x] create handlebars profile view - issue #37
- [x] add edit button option for each section - issue #38
- [x] Save job data from profile - issue #93
- [x] Profile update modal - add close without saving button - issue #94

Edit profile form mode:
![edit profile details](https://i.imgur.com/f42bYPa.png)

View profile mode:
![profile](https://i.imgur.com/d8jKzTw.png)

**Comment by helenzhou6** [comment]
Relate to user journey: #5
