### ISSUE TITLE
As a FAC grad, I can click a button to log out

### ISSUE THREAD

**Issue by vlbee** [fac-13/stackMatch#9]
**Acceptance Criteria**

- [x] Add logout route & oAuth handler - issue #39
- [x] Add logout button to relevant views  - issue #40
- [x] add event listener to logout button wherever it appears  - issue #41

**Comment by helenzhou6** [comment]
Relate to user journey: #5
